on:
  push:
  workflow_dispatch:
name: 'markdown-auto'
jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'dineshsonachalam/markdown-autodocs@v1.0.4'
        with:
          commit_message: 'README.md files have been updated'
          output_file_paths: '[./README.md]'
