on:
  schedule:
    - cron: '0 1 * * 4'
  workflow_dispatch:

name: 'storage/create/README.md'
jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - run: |
          chmod +x ${GITHUB_WORKSPACE}/setup-env.sh
          chmod +x ${GITHUB_WORKSPACE}/core-group/group-create/group-create.sh
          chmod +x ${GITHUB_WORKSPACE}/storage-storage/storage-create/storage-create.sh
          chmod +x ${GITHUB_WORKSPACE}/core-group/group-delete/group-delete.sh

          sh ${GITHUB_WORKSPACE}/setup-env.sh
          sh ${GITHUB_WORKSPACE}/core-group/group-create/group-create.sh
          sh ${GITHUB_WORKSPACE}/storage-storage/storage-create/storage-create.sh
          sh ${GITHUB_WORKSPACE}/core-group/group-delete/group-delete.sh
        shell: bash
