on:
  schedule:
    - cron: '0 1 * * 4'
  workflow_dispatch:

name: 'storage/create/README.md'
jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - run: |
          chmod +x ./setup-env.sh
          ./setup-env.sh
        shell: bash
      - run: |
          chmod +x ./core-group/group-create/group-create.sh
          ./core-group/group-create/group-create.sh
        shell: bash
      - run: |
          chmod +x ./storage-storage/storage-create/storage-create.sh
          ./storage-storage/storage-create/storage-create.sh
        shell: bash
      - run: |
          chmod +x ./core-group/group-delete/group-delete.sh
          ./core-group/group-delete/group-delete.sh
        shell: bash
